In [ ]:
import numpy as np

In [ ]:
# 1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
arr=np.arange(30)
arr.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
# 2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr=np.random.randint(0,100,60)
arr=arr.reshape(3,5,-1)
print(arr.ndim)
print(arr.shape)

3
(3, 5, 4)


In [ ]:
# 3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr=np.random.randint(0,10, size=(4,5))
arr=arr.reshape(-1)
print(arr.ndim)
print(arr.shape)

1
(20,)


In [ ]:
# 4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
arr=np.random.randint(10, size=(2,3))
print(arr)

for i in arr:
  for j in i:
    print(j)
print(" ")
for i in np.nditer(arr): print(i)

[[8 5 6]
 [3 3 2]]
8
5
6
3
3
2
 
8
5
6
3
3
2


In [ ]:
''' 5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.'''
  
arr_1=np.array([5,10,15,20,25,30])
arr_2=np.array([1,2,3,4,5,6])

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]


In [ ]:
#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
arr=np.random.randint(0,100,10)
print(arr)
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.var())
print(arr.std())

[ 3 84 76 25 74 96 52 17 75 72]
574
57.4
96
901.24
30.020659553047796


In [ ]:
# 7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
arr_1=np.arange(0,20)
arr_2=np.arange(500,531)
np.concatenate([arr_1,arr_2])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [ ]:
# 8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
arr_1=np.arange(0,51)
arr_2=np.arange(10,101)
arr=np.concatenate([arr_1,arr_2])
arr[25:51]=888
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  10,
        11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# 9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
arr_1=np.arange(0,40).reshape(8,5)
arr_2=np.arange(320,360).reshape(8,5)
arr1=np.concatenate([arr_1,arr_2],axis=0)
arr2=np.concatenate([arr_1,arr_2],axis=1)
print(arr1)
print(arr2)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]


In [ ]:
# 10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
arr3=np.concatenate([arr_1,arr_2], axis=2)
arr4=np.stack([arr_1,arr_2] , axis = 2)
print(arr3)
print(arr4)

AxisError: ignored

In [57]:
# 11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
arr=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
for i in range(len(arr)):
    if arr[i] == 5:
      print(i)


5
13


In [58]:
# 12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
for i in range(len(arr)):
    if arr[i] % 5:
      print(i)

0
3
4
6
7
8
9
10
11
12


In [59]:
# 13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
for i in range(len(arr)):
    if arr[i]>4:
      print(i)

1
2
5
9
10
11
13


In [60]:
# 14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
for i in range(len(arr)):
    if arr[i]//5==0:
      print(i)

0
3
4
6
7
8
12


In [61]:
# 15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
np.random.randint(85,101,1)

array([87])

In [63]:
# 16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
arr=np.random.randint(10,100,size=(3,3))
arr

array([[29, 75, 97],
       [59, 76, 21],
       [12, 96, 56]])

In [67]:
# 17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
arr=np.arange(35,60)
random_num = np.random.choice(arr)
random_num

50

In [72]:
# 18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.
my_list = [3, 8, 10, 53]
my_array = np.array([my_list, my_list])
print(my_array)

[[ 3  8 10 53]
 [ 3  8 10 53]]
